package org.botai.back.grading;

import org.botai.back.catalog.CatalogService;
import org.botai.back.common.*;
import org.botai.back.grading.port.GradingGateway;
import org.botai.back.media.MediaService;
import org.botai.back.media.port.ObjectStorage;
import org.botai.back.profile.ProfileService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.*;
import org.springframework.stereotype.Component;
import org.springframework.transaction.support.TransactionTemplate;
import jakarta.annotation.PreDestroy;
import java.util.*;
import java.util.concurrent.*;

@Component
@EnableScheduling
public class GradingWorker {
    public record Claim(UUID submission,long fence) { }
    private final SubmissionStore store;private final SubmissionService service;private final CatalogService catalog;private final ProfileService profile;private final ObjectStorage storage;private final GradingGateway gateway;private final TransactionTemplate tx;private final MediaService media;private final boolean enabled;
    private final ExecutorService workers=Executors.newFixedThreadPool(2);private final Semaphore slots=new Semaphore(2);private final AiResponseValidator validator=new AiResponseValidator();
    public GradingWorker(SubmissionStore store,SubmissionService service,CatalogService catalog,ProfileService profile,ObjectStorage storage,GradingGateway gateway,TransactionTemplate tx,MediaService media,@Value("${app.grading.worker-enabled:true}")boolean enabled){this.store=store;this.service=service;this.catalog=catalog;this.profile=profile;this.storage=storage;this.gateway=gateway;this.tx=tx;this.media=media;this.enabled=enabled;}
    @Scheduled(fixedDelay=1000) public void poll(){if(!enabled)return;while(slots.tryAcquire()){Claim claim;try{claim=claim();}catch(Exception e){slots.release();return;}if(claim==null){slots.release();return;}workers.submit(()->{try{execute(claim);}finally{slots.release();}});}}
    public Claim claim(){return tx.execute(t->{var rows=store.db().queryForList("SELECT submission_id,fencing_token FROM grading_jobs WHERE state='ready' AND available_at<=now() ORDER BY available_at,submission_id LIMIT 1 FOR UPDATE SKIP LOCKED");if(rows.isEmpty())return null;var row=rows.getFirst();UUID id=(UUID)row.get("submission_id");long fence=((Number)row.get("fencing_token")).longValue()+1;store.db().update("UPDATE grading_jobs SET state='claimed',fencing_token=?,lease_until=now()+interval '90 seconds',updated_at=now() WHERE submission_id=?",fence,id);return new Claim(id,fence);});}
    public UUID dispatch(Claim claim){return tx.execute(t->{var s=store.row(claim.submission,null,true);if(!s.status().equals("queued"))return null;UUID run=UUID.randomUUID();int changed=store.db().update("UPDATE grading_jobs SET state='dispatching',run_id=?,lease_until=now()+interval '420 seconds',updated_at=now() WHERE submission_id=? AND state='claimed' AND fencing_token=? AND lease_until>now()",run,claim.submission,claim.fence);if(changed!=1)return null;store.db().update("INSERT INTO grading_runs(id,submission_id,fencing_token,package_id) VALUES(?,?,?,?)",run,claim.submission,claim.fence,s.packageId());store.db().update("UPDATE grading_submissions SET status='running',revision=revision+1,updated_at=now() WHERE id=?",claim.submission);store.event(claim.submission,"dispatch_committed",null,Map.of("runId",run,"fencingToken",claim.fence));return run;});}
    public void execute(Claim claim){boolean dispatched=false;try{var s=store.row(claim.submission,null,false);var task=catalog.snapshot(s.version());var images=new ArrayList<GradingGateway.Image>();for(var row:store.db().queryForList("SELECT id,object_key,mime_type FROM stored_objects WHERE submission_id=? AND state='ready' ORDER BY ordinal",s.id()))images.add(new GradingGateway.Image((UUID)row.get("id"),storage.get((String)row.get("object_key"),8*1024*1024),(String)row.get("mime_type")));if(images.isEmpty()||images.size()>4)throw new ApiException(422,"images_missing","Изображения недоступны");UUID run=dispatch(claim);if(run==null)return;dispatched=true;var response=gateway.grade(run,task,images,s.packageId());var validated=validator.validate(response,task,images,s.packageId(),s.mode());complete(claim,response,validated);
        }catch(Exception e){fail(claim,dispatched?(e instanceof ApiException a?a.code():"unknown_after_dispatch"):"storage_unavailable",dispatched);}}
    public void complete(Claim claim,GradingGateway.Response response,AiResponseValidator.Validated result){tx.executeWithoutResult(t->{var s=store.row(claim.submission,null,true);if(!live(claim,"dispatching")||!s.status().equals("running")){store.event(s.id(),"late_result_ignored",null,Map.of("responseHash",JsonCodec.sha256(response.exactJson()),"providerMode",response.providerMode()));return;}var task=catalog.snapshot(s.version());store.db().update("UPDATE grading_submissions SET status=?,is_demo=?,provider_mode=?,revision=revision+1,finished_at=now(),updated_at=now() WHERE id=?",result.graded()?"graded":"rejected",result.demo(),response.providerMode(),s.id());service.result(s,result.graded(),result.score(),task.maxScore(),result.feedback(),result.rejectionReason(),result.demo(),response.exactJson(),response.providerMode(),response.packageId());store.db().update("UPDATE grading_runs SET provider_mode=?,outcome=?,finished_at=now() WHERE submission_id=? AND fencing_token=?",response.providerMode(),result.graded()?"graded":"rejected",s.id(),claim.fence);store.db().update("UPDATE grading_jobs SET state='done',lease_until=NULL,updated_at=now() WHERE submission_id=?",s.id());var metadata=new HashMap<String,Object>();metadata.put("isDemo",result.demo());if(response.rejectionCode()!=null)metadata.put("rejectionCode",response.rejectionCode());store.event(s.id(),result.graded()?"graded":"ai_rejected",null,metadata);if(result.graded())profile.acceptGraded(s.user(),task.id(),s.id(),result.score(),task.maxScore(),result.demo());store.touchAttempt(s.attempt());});}
    private boolean live(Claim claim,String state){return store.db().queryForObject("SELECT count(*) FROM grading_jobs WHERE submission_id=? AND fencing_token=? AND state=? AND lease_until>now()",Integer.class,claim.submission,claim.fence,state)==1;}
    public void fail(Claim claim,String code,boolean dispatched){tx.executeWithoutResult(t->{var s=store.row(claim.submission,null,true);if(!live(claim,dispatched?"dispatching":"claimed")||!Set.of("queued","running").contains(s.status())){store.event(s.id(),"late_failure_ignored",null,Map.of("code",code));return;}store.terminal(s,"failed",code);store.db().update("UPDATE grading_jobs SET state='done',lease_until=NULL,updated_at=now() WHERE submission_id=?",s.id());store.db().update("UPDATE grading_runs SET outcome=?,finished_at=now() WHERE submission_id=? AND fencing_token=?",code,s.id(),claim.fence);});}
    @Scheduled(fixedDelay=30000) public void reconcile(){if(!enabled)return;reap();media.reap();}
    public void reap(){var expired=store.db().queryForList("SELECT submission_id,fencing_token,state FROM grading_jobs WHERE state IN('claimed','dispatching') AND lease_until<now() LIMIT 100");for(var row:expired)tx.executeWithoutResult(t->{UUID id=(UUID)row.get("submission_id");var s=store.row(id,null,true);var jobs=store.db().queryForList("SELECT state FROM grading_jobs WHERE submission_id=? AND fencing_token=? AND lease_until<now() AND state IN('claimed','dispatching') FOR UPDATE",id,row.get("fencing_token"));if(jobs.isEmpty())return;String state=(String)jobs.getFirst().get("state");if(state.equals("claimed")&&s.status().equals("queued")){store.db().update("UPDATE grading_jobs SET state='ready',fencing_token=fencing_token+1,lease_until=NULL,updated_at=now() WHERE submission_id=?",id);store.event(id,"pre_dispatch_requeued",null,Map.of());}else{if(Set.of("running","queued").contains(s.status()))store.terminal(s,"failed","unknown_after_dispatch");store.db().update("UPDATE grading_jobs SET state='done',fencing_token=fencing_token+1,lease_until=NULL,updated_at=now() WHERE submission_id=?",id);store.db().update("UPDATE grading_runs SET outcome='unknown_after_dispatch',finished_at=now() WHERE submission_id=? AND outcome IS NULL",id);}});}
    @PreDestroy void close(){workers.shutdownNow();}
}
